version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test_usr
      - MYSQL_PASSWORD=mdp
      - MYSQL_ROOT_PASSWORD=mdp